---
target:
  base-url: https://api.github.com/repos
  repos:
    keyno63:
      - ts-sandbox
      - go-mod-sandbox

request:
  page-num: 100

slack:
  web-hook-path: ""
  base-url: "https://hooks.slack.com/services"
