---
target:
  base-url: https://api.github.com/repos
  repos:
    keyno63:
      - ts-sandbox
      - go-mod-sandbox

request:
  issues:
    page-num: 100
    span: 7 # days
  pulls:
    page-num: 100
    span: 7 # days

slack:
  web-hook-path: ""
  base-url: "https://hooks.slack.com/services"
